version: "3.6"
volumes:
  war-volume:

services:

  mvn:
    build: ./mvn_server/
    volumes:
    - type: volume
      source: war-volume
      target: /tmp/war
  

  tomcat:
    build: ./tomcat_server/
    ports:
      - "80:8080"
    volumes:
      - type: volume
        source: war-volume
        target: /tmp/war-src
    depends_on: 
      - mvn