version: "3.6"
volumes:
  war-volume:

services:

  mvn:
    build: ./mvn_server/
    volumes:
    - type: volume
      source: war-volume
      target: /tmp/war

  tomcat:
    image: nirmata/tomcat9-alpine-jre12-openjdk
    ports:
      - "80:8080"
    volumes:
      - type: volume
        source: war-volume
        target: /usr/local/tomcat/webapps/
    depends_on: 
      - mvn
